### ISSUE TITLE
只能用国密链吗？

### ISSUE THREAD

**Issue by BrownTan** [YibiOpen/evidence-chain-demo#7]
之前一直部署的都是不支持国密的节点和webase，部署该项目时也成功了，可以访问端口，直到登录后初始化部署存证合约时报错“Request failed with status code 500”，请问是不是因为没有使用国密链的原因？

**Comment by ClaireDad** [comment]
请问您解决了吗，我也遇到这个问题了

**Comment by BrownTan** [comment]
> 请问您解决了吗，我也遇到这个问题了
已解决，是因为版本问题导致的参数格式不同

**Comment by ClaireDad** [comment]
是fisco bcos需要使用2.6版本这个问题吗

**Comment by BrownTan** [comment]
具体我忘掉了，要么是webase要么是fiscobcos的问题

**Comment by ClaireDad** [comment]
能找到之前的信息吗，这对我很重要，能帮帮忙嘛

**Comment by ClaireDad** [comment]
我复现这个项目快一周了，最后一直卡在这个状态500这边

**Comment by BrownTan** [comment]
Okay, but something went wrong with VMware some time ago and I uninstalled it。it may take a while to search for this information

**Comment by ClaireDad** [comment]
Thank you so much, your help means a lot to me, I went from day to night, asked the tutor, and they didn't help me as much as you did

**Comment by BrownTan** [comment]
follow me,then you will get the answer

**Comment by ClaireDad** [comment]
Okay, I've already followed you

**Comment by BrownTan** [comment]
Damn it! GitHub does not support private messages.

**Comment by BrownTan** [comment]
It is an error caused by a version problem with webase, please leave your contact information and I will send you the details.

**Comment by ClaireDad** [comment]
Do you use QQ or WeChat

**Comment by BrownTan** [comment]
the latter is more often

**Comment by ClaireDad** [comment]
w2499474643

**Comment by BrownTan** [comment]
ok,you can delete it.
